# General config for student service and faculty service
eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-54-179-190-119.ap-southeast-1.compute.amazonaws.com:8761/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: GardenService
          uri: lb://GardenService
          predicates:
            - Path=/api/gardens/**
        - id: TreeService
          uri: lb://TreeService
          predicates:
            - Path=/api/trees/**

