spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: GardenService
          uri: lb://GardenService
          predicates:
            - Path=/api/gardens/**
        - id: TreeService
          uri: lb://TreeService
          predicates:
            - Path=/api/trees/**
eureka:
  client:
    serviceUrl:
      defaultZone: https://ec2-54-179-25-25.ap-southeast-1.compute.amazonaws.com:8761/eureka
  instance:
    preferIpAddress: true
